wine_shop/accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

wine_shop/wine/urls.py
from django.urls import path, include
from . import views

app_name = 'wine'
urlpatterns = [

    path('', views.search, name='search'),

    ]

wine_shop/wine_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('wine/', include('wine.urls', namespace='wine')),


]

wine_shop/accounts/models.py
from django.db import models

# Create your models here.

wine_shop/wine/models.py
from django.db import models


class Wine(models.Model):
    country = models.CharField(max_length=500, blank=True)
    description = models.TextField(blank=True)
    designation = models.CharField(max_length=500, blank=True)
    points = models.IntegerField(blank=True)
    price = models.IntegerField(blank=True)
    province = models.CharField(max_length=500, blank=True)
    region_1 = models.CharField(max_length=500,blank=True)
    region_2 = models.CharField(max_length=500,blank=True)
    variety = models.CharField(max_length=500, blank=True)
    winery = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.country

wine_shop/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

wine_shop/wine/views.py
from .models import Wine
from django.shortcuts import render
from .filters import WineFilter
from django.contrib.auth.decorators import login_required

@login_required
def search(request):
    if request.method == 'GET':
        wine_list = Wine.objects.all()
        wine_filter = WineFilter(request.GET, queryset=wine_list)
        return render(request, 'wine.html', {'filter':wine_filter})

wine_shop/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Wines{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
     {% block content %}
     {% endblock %}
            </div>
    </div>


</body>
</html>

wine_shop/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1> Welcome to Wine shop</h1>
<span ><a href="{% url 'wine:search' %}">See list of wines here </a></span>

{% if user.is_authenticated %}
<br>
  <h2> Hi {{ user.username }}!</h2>
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
  <br>
  <p>Or</p>
  <a href="{% url 'signup' %}">Signup</a>
{% endif %}
{% endblock %}

wine_shop/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

wine_shop/templates/wine.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {% block content %}

    <form method="get">
        {{ filter.form|crispy }}

        <button type="submit">Search</button>

    </form>
<br>
<br>

    <ul class="list-group">
        {% for wine in filter.qs %}

            <li class="list-group-item active">
                <b>Country: </b> {{ wine.country }}
            </li>
            <li class="list-group-item">
                <b>Price: </b> {{ wine.price }}
            </li>
        <li class="list-group-item">
                 <b>Description: </b> {{ wine.description }}
            </li>
        <li class="list-group-item">
                 <b>Designation: </b> {{ wine.designation }}
            </li>
        <li class="list-group-item">
                <b>Province: </b> {{ wine.province  }}
            </li>
        <li class="list-group-item">
                  <b>Province: </b> {{ wine.province  }}
            </li>
        <li class="list-group-item">
                 <b>Region_1: </b> {{ wine.region_1 }}
            </li>
        <li class="list-group-item">
               <b>Region_2: </b>{{ wine.region_2 }}
            </li>
        <li class="list-group-item">
                <b>Variety: </b> {{ wine.variety }}
            </li>
        <li class="list-group-item">
                <b>Winery: </b> {{ wine.winery }}
            </li>


        {% endfor %}

    </ul>
    {% endblock %}